### ISSUE TITLE
Investigate reducing the default minimum similarity to something lower than (0.8)

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#3532]
I have been wanting to experiment with this for a while.  Mentioned it to Matt a couple of time prior to switching over to Iris2.  Today I fixed a few test cases that were all failing for the same reason;  Patterns with text in them didn't find matches until the similarity was reduced to (0.6).  I have a feeling many other tests are failing from the very same problem. 

I want to investigate if changing the default similarity for Iris will have any effect on test run stability.  I'll track and report my findings here.

**Comment by tracywalker** [comment]
Initial findings with the awesomebar test group are encouraging.  Run with current default produced 8 failures that includes the 4 tests I recently fixed by adjusting particular pattern similarity to (0.6).  So actual failure in (0.8) would be 12 test failures. Run with the default similarity for pattern matching set to (0.6) produced 6 failures.

So far, so good.  I'll do similar comparisons on a few other test groups. The main thing I am concerned with by reducing similarity is getting false positives in critical test asserts.  I'll have to keep an eye out for that.

**Comment by pavelciapa** [comment]
I noticed same behaviour few days ago, and playing with similarity doesn't fix a failure, despite an image seems to be on screen, and pattern is similar to it.

I think the reason is in Firefox core style updates. Some random UI elements, font settings are affected, didn't find the regularity yet.

**Comment by pavelciapa** [comment]
Example 1:
![image](https://user-images.githubusercontent.com/45387203/61855588-df471c00-aeaf-11e9-909e-e68200bf0935.png)


Example 2(zoomed and dragged):

![image](https://user-images.githubusercontent.com/45387203/61856168-2386ec00-aeb1-11e9-8b2b-851aab33d291.png)

**Comment by tracywalker** [comment]
In some cases, there may be a notable style change that similarity doesn't affect.  However, I have been working on this project long enough to know that there are plenty of patterns containing text that Iris fails to find a match because the default similarity is too high.   My recent spell of test fixes highlights that point.

I am investigating if we can safely lower the default similarity.  Sighting one example of a pattern that changing similarity doesn't fix a pattern match isn't going to halt my investigation.

**Comment by tracywalker** [comment]
I don't expect a default similarity change to solve all the problems with patterns containing text.  If doing so fixes a reasonable amount of failures and doesn't regression other pattern matching. There is potential fr a big enough win, that it is worth investigating.

As far as your example above, are you sure that failure is caused by a recent style change in Firefox?  Is it possible the original pattern wasn't captured in the same locale version of Firefox as that which is under test?

**Comment by pavelciapa** [comment]
> As far as your example above, are you sure that failure is caused by a recent style change in Firefox? Is it possible the original pattern wasn't captured in the same locale version of Firefox as that which is under test?

- I can't be sure if there were changes in Firefox styles. I've noticed few similar failures while we were categorizing test failures last days. 
- I am sure that locale and preferences and which original pattern for test was captured are the same as we launch Iris, and make patterns via Sikuli in Iris's Firefox window

**Comment by tracywalker** [comment]
Results for Bookmarks test group don't look as good as they did for awesomebar.
on `master`branch:
default similarity at 0.8 - 12 tests failed.  
default similarity at 0.6 - 32 tests failed. 

An increase in failure rate for 0.6 similarity vs 0.8 indicates false positive matches during test steps, leading to incorrect/failed test execution. As such, I think it will be too risky to change the default minimum similarity. 

We'll have to continue to address pattern matching issues that are similarity related on an as needed basis.

**Comment by pavelciapa** [comment]
Today I've faced another issue.
Just created pattern for test via Sikuli, was not matched on default similarity at the same machine I just created a pattern. Lowering to `similar(0.7)` fixed this

**my small conclusions:**
- lowering default similarity make sense
- look deeper into Sikuli's algorithm of image creation

**Comment by tracywalker** [comment]
Per Sikuli documentation, "Sikuli searches the region using a default minimum similarity of 0.7."  

Not sure why we aren't the same. Iris should probably be in-line with Sikulki here. Re-opening this issue.  I'll do some more test group testing with (0.7)

**Comment by pavelciapa** [comment]
https://github.com/mozilla/iris_firefox/blob/3eda0b5126065c4107dea820eaff90cee820b754/tests/firefox/awesomebar/images/osx/result_is_focused.png

This image required 0.7

**Comment by tracywalker** [comment]
I ran bookmarks test group again at (0.7)
default similarity at 0.7 - 12 tests failed.

same number of failures as with 0.8.

**Comment by tracywalker** [comment]
Didn't mean to close this.  More testing required. But I think we might be able to and probably should change default similarity to (0.7)

**Comment by tracywalker** [comment]
Let's get our test case fixing work completed. Then try some full test runs at (0.7)  I think there will be some unexpected failures.  But We won't be able to sort it out without first getting to clean test runs first.

**Comment by pavelciapa** [comment]
> Then try some full test runs at (0.7) 

why wouldn't we try some medium value like (0.75) ?

**Comment by tracywalker** [comment]
We can try multiple values to compare what effect each has on test runs.

We can't do any sort of detailed comparison until our test runs are clean.

**Comment by tracywalker** [comment]
I'm seeing enough tests begin to pass if default similarity if it is set to 0.7.  I'm going to make that change now.
